from io import BytesIO
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor

styles = getSampleStyleSheet()

title_style = styles["Heading1"]
title_style.alignment = TA_CENTER
title_style.textColor = HexColor("#0ea5e9")

heading = styles["Heading2"]
heading.textColor = HexColor("#2563eb")

normal = styles["BodyText"]


def generate_report_pdf(report):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    elements = []

    elements.append(
        Paragraph(
            "NeuroBridge AI",
            title_style
        )
    )

    elements.append(
        Paragraph(
            "AI Assessment Report",
            heading
        )
    )

    elements.append(Spacer(1, 20))

    # --- FIX: Added missing Student Name and ID to the PDF ---
    student_name = report.get("student_name") or report.get("name") or "Unknown Student"
    elements.append(
        Paragraph(
            f"<b>Student Name:</b> {student_name}",
            normal
        )
    )

    elements.append(
        Paragraph(
            f"<b>Student ID:</b> {report.get('student_id', 'N/A')}",
            normal
        )
    )

    elements.append(
        Paragraph(
            f"<b>Report Type:</b> {report.get('report_type', 'N/A').title()}",
            normal
        )
    )

    elements.append(Spacer(1, 12))

    # SCREENING REPORT
    # FIX: Used .get() for all dictionary keys to prevent crashes if a field is missing
    if report.get("report_type") == "screening":

        elements.append(
            Paragraph(
                "<b>Observations</b>",
                heading
            )
        )

        elements.append(
            Paragraph(
                str(report.get("observations", "No observations recorded.")),
                normal
            )
        )

        elements.append(Spacer(1, 12))

        elements.append(
            Paragraph(
                f"<b>Possible Condition:</b> {report.get('possible_condition', 'N/A')}",
                normal
            )
        )

        elements.append(
            Paragraph(
                f"<b>Risk Level:</b> {report.get('risk_level', report.get('risk', 'N/A'))}",
                normal
            )
        )

        elements.append(
            Paragraph(
                f"<b>Confidence:</b> {report.get('confidence', 'N/A')}%",
                normal
            )
        )

        elements.append(
            Paragraph(
                f"<b>Strengths:</b> {report.get('strengths', 'N/A')}",
                normal
            )
        )
        
        # Safely handle lists if the AI returns an array for recommendations
        recs = report.get('recommendation', report.get('recommendations', 'N/A'))
        if isinstance(recs, list):
            recs = ", ".join(recs)

        elements.append(
            Paragraph(
                f"<b>Recommendation:</b> {recs}",
                normal
            )
        )

    # COMMUNICATION REPORT
    else:

        elements.append(
            Paragraph(
                "<b>Student Statement</b>",
                heading
            )
        )

        elements.append(
            Paragraph(
                str(report.get("student_text", "No statement recorded.")),
                normal
            )
        )

        elements.append(Spacer(1, 12))

        elements.append(
            Paragraph(
                f"<b>Simplified Meaning:</b> {report.get('simplified', 'N/A')}",
                normal
            )
        )

        elements.append(
            Paragraph(
                f"<b>Emotion:</b> {report.get('emotion', 'N/A')}",
                normal
            )
        )

        elements.append(
            Paragraph(
                f"<b>Confidence:</b> {report.get('confidence', 'N/A')}%",
                normal
            )
        )

        elements.append(
            Paragraph(
                f"<b>Risk:</b> {report.get('risk', 'N/A')}",
                normal
            )
        )

        elements.append(
            Paragraph(
                f"<b>Teacher Suggestion:</b> {report.get('suggestion', 'N/A')}",
                normal
            )
        )

    elements.append(Spacer(1, 30))

    elements.append(
        Paragraph(
            "Generated by NeuroBridge AI",
            styles["Italic"]
        )
    )

    doc.build(elements)

    buffer.seek(0)

    return buffer